- README.md
- package.json
- src/lib/mollie/api/object/method.coffee
While I was at it, I figured it couldn't hurt to alphabetically sort the payment method constants. Furthermore, I added the `giftcard` method, as it was missing.
I updated the README to include the appropriate text for the new payment methods, but as the links to the respective payment methods are not present yet, I could not add links yet.
> Added Giropay and EPS support

- README.md
Hi! I'm trying out this package and I spotted a small mistake in the docs:
- Corrects a small mistake in the README example. The amount is a number instead of a string which will make the API respond with a 422.
> Convert amount from number to string in README example

- examples/02-webhook-verification.js
Hi,
I was testing the API and I came across a small mistake in the way the webhook is called in the example file. Shouldn't the method be 'POST'? If you try with 'GET' you get a 404.
Thanks,
Tania
> Change webhook call from 'GET' to 'POST'

- .babelrc
- .travis.yml
- package.json
- rollup.config.js
- tests/unit/resources/__snapshots__/chargebacks.test.js.snap
- tests/unit/resources/__snapshots__/customers.test.js.snap
- tests/unit/resources/__snapshots__/methods.test.js.snap
- tests/unit/resources/__snapshots__/payments.test.js.snap
- tests/unit/resources/__snapshots__/refunds.test.js.snap
- tests/unit/resources/customers/__snapshots__/mandates.test.js.snap
- tests/unit/resources/customers/__snapshots__/payments.test.js.snap
- tests/unit/resources/customers/__snapshots__/subscriptions.test.js.snap
- tests/unit/resources/payments/__snapshots__/refunds.test.js.snap
- yarn.lock
There are currently 10 vulnerability alerts for the Node API module. I've upgraded most of our dependencies (they were quite outdated) and now most of them are gone.
Unfortunately, we need to drop support for Node 4.8 since we have updated ESLint. However, as we already discussed in our TypeScript migration PR (#97), this doesn't have to be a breaking change as it's not used that much.
Last week [another advisory was published](https://www.npmjs.com/advisories/788), but I need to wait for my [ESLint PR to be approved](https://github.com/eslint/eslint/pull/11550) & released before we can fix that alert as well.
**Release strategy**
Before actually releasing this, I'd like to release a beta version of the API client to test it in some example projects.
> DASH-1618 - Fix vulnerability alerts

- CHANGELOG.md
- MIGRATION.md
Is this the correct migration guide link? Please check.
> Two small fixes in the documentation

- examples/orders/create_payment.js
- examples/orders/create_payment.ts
- src/createMollieClient.ts
- src/resources/orders/payments.ts
- src/types/order/payment/params.ts
- tests/unit/resources/orders/payments.test.ts
I saw that this feature was missing in the node library: https://docs.mollie.com/reference/v2/orders-api/create-order-payment, so I took the effort to implement it for you guys :)
> add orders_payments api

- src/types/mandate/index.ts
I saw, that paypal as mandate method was missing in the typescript types, but it is available according to the docs: https://docs.mollie.com/reference/v2/subscriptions-api/create-subscription
> add paypal mandate method

- README.md
Running `npm view @mollie/api-client versions` results in this:
[
'2.0.0',        '2.0.1',
'2.0.3',        '2.1.0',
'2.1.1',        '2.1.2',
'2.2.0',        '2.3.0',
'2.3.1',        '2.3.2',
'3.0.0-beta.1', '3.0.0',
'3.1.0'
]
It should be safe to remove the `@beta` part from the installation instructions.
> remove @beta from installation instructions.

- src/resources/Resource.ts
We've been joining the embed arguments with a `;` [for a year now](https://github.com/mollie/mollie-api-node/blob/695b23c55f10bc4eaa72fed32602d9e394ce3450/src/resource.ts#L141), but [it looks like](https://github.com/mollie/api-documentation/blob/master/source/reference/v2/orders-api/get-order.rst#example) it should have been joined with a `,` all along.
This fixes #144.
> Fix embedding multiple resources

- src/resources/orders/parameters.ts
According to the documentation you can pass `expiresAt` when creating an order.
https://docs.mollie.com/reference/v2/orders-api/create-order#parameters
> include `expiresAt` in order creation parameters

- package.json
- yarn.lock
This fixes https://github.com/advisories/GHSA-6c8f-qphg-qjgp.
Unfortunately, not all dependencies have released new versions that depend on the latest version of the `kind-of` dependency. Therefore, I suggest fixing this using selective dependency resolutions.
We should plan a moment to revisit all dependencies and upgrade the ones that released a patch. This will most likely allow us to clean up the other selective dependency resolutions as well.
> Upgrade `kind-of` dependency to fix security vulnerability

- src/resources/orders/parameters.ts
Fixed the `CreateParameters` used by `mollieClient.orders.create`. See [docs.mollie.com/reference/v2/orders-api/create-order](https://docs.mollie.com/reference/v2/orders-api/create-order).
This fixes #157.
> Fix types for mollieClient.orders.create

- package.json
- rollup.config.js
- src/resources/Resource.ts
- yarn.lock
We have been using the external [`qs`](https://www.npmjs.com/package/qs) library since 2.0.0, although Node.js provides an alternative out-of-the-box. (This works in Node.js 6 as well. It was introduced in Node.js 0.1.25, to be exact).
> Use Node.js' querystring instead of the external qs

- .eslintrc
- examples/subscriptions/list-payments.js
- examples/subscriptions/list-payments.ts
- src/createMollieClient.ts
- src/resources/subscriptions/payments/SubscriptionsPaymentsResource.ts
- src/resources/subscriptions/payments/parameters.ts
- tests/unit/resources/subscriptions/payments.test.ts
I added functionalities for this endpoint in NodeJS SDK: https://docs.mollie.com/reference/v2/subscriptions-api/list-subscriptions-payments . We need to use it for one of our clients and I really appreciate if you can review and release a new version ASAP.
> Add subscriptions_payments api

- src/createMollieClient.ts
- tests/unit/networking.test.ts
- tests/wireMockClient.ts
Added `apiEndpoint` property to the options passed to `createMollieClient`.
I did not add any documentation, as I feel this feature doesn't require any extra discoverability. This is a feature which will not be of interest to the average user.
Fixes #164.
> apiEndpoint option

- src/resources/Resource.ts
- tests/unit/networking.test.ts
In commit 886de38650d120e0be2a85e97e676e5cf9d87597, we switched from [an external alternative](https://www.npmjs.com/package/qs) to [Node.js' querystring module](https://nodejs.org/api/querystring.html).
Unbeknownst to me, said external alternative has special logic for nested objects on which we rely [in a specific endpoint](https://docs.mollie.com/reference/v2/methods-api/list-all-methods). This commit adds that special logic to our codebase.
Additionally, I added a test to verify the behaviour of `stringifyQuery` with objects.
Fixes #165.
> stringifyQuery fix

- src/resources/Resource.ts
- src/resources/payments/PaymentsResource.ts
[According to the documentation](https://docs.mollie.com/reference/v2/payments-api/create-payment#qr-codes), the `include` property should be included in the query string instead of the body.
Fixes #168.
> Pass include (payments.create) in the query string instead of the body

- src/resources/orders/parameters.ts
[According to the documentation](https://docs.mollie.com/reference/v2/orders-api/update-order), it is possible to update the redirect and webhook URLs for orders. Therefore, the associated properties are now included in the parameters type.
Fixes #169.
> Add parameters to orders.update

- src/resources/orders/parameters.ts
This PR adds testmode and profileId to CreateParameters for Order.
To ensure this can be used when using Mollie Connect if you're relying on TypeScript to ensure type safety.
> Add profileId and testmode to order creation parameters

- src/resources/Resource.ts
- src/resources/orders/OrdersResource.ts
- src/resources/orders/parameters.ts
According to the Documentation page - `embed` query param could be passed to fetch the payment data of the newly created Order.
https://docs.mollie.com/reference/v2/orders-api/create-order#embedding-of-related-resources
Besides that, `query` param in `post` method (added [here](https://github.com/mollie/mollie-api-node/pull/172/files)) was not used at all.
> Adding `embed` param to Orders.create method

- src/resources/orders/shipments/parameters.ts
Lines should be optional in the shipments api (according to the API docs)
> Lines is optional in the shipments api

- src/NetworkClient.ts
- src/resources/Resource.ts
The [Node.js URL API](https://nodejs.org/api/url.html#url_legacy_urlobject) was deprecated in Node.js 11, while the [WHATWG counterpart](https://url.spec.whatwg.org/) is supported since Node.js 7 and 6.13.
Our lowest supported Node.js version is currently 6.14.
> Replace Node.js URL API for WHATWG URL API.

- src/resources/payments/parameters.ts
Make it possible to create an apple pay payment when using typescript.
This will otherwise throw a "not assignable" error.
> Add applePayPaymentToken to payment parameters

- src/data/global.ts
- src/data/payments/data.ts
- src/resources/customers/payments/parameters.ts
- src/resources/orders/parameters.ts
- src/resources/payments/orders/parameters.ts
- src/resources/payments/parameters.ts
This reflects [the discontinuation of ING Home'Pay](https://docs.mollie.com/changelog/v2/changelog#february-2021) in the library.
> Update documentation from docs.mollie.com.

- src/errors/ApiError.ts
- tests/unit/errors.test.ts
This makes it more likely that the message survives serialisation. (`message` is not enumerable by default<sup>[[source]](https://tc39.es/ecma262/#sec-error-message)</sup>.)
Given that this client is designed for Node.js, consumers might convert errors to JSON. This way, the message ends up in the resulting JSON document.
> Make message of ApiError instances enumerable

- src/resources/customers/mandates/parameters.ts
Updated the CreateParameters for mandates to support PayPal option.
Like here: 
https://docs.mollie.com/reference/v2/mandates-api/create-mandate
> Add Paypal Support

- src/plumbing/buildFromEntries.ts
- src/plumbing/getEntries.ts
- src/resources/Resource.ts
This makes it clearer why we're not using `Object.fromEntries` directly, and allows us to use `Object.fromEntries` under the hood when available.
> Isolate buildFromEntries

- src/createMollieClient.ts
- src/data/customers/mandates/MandateHelper.ts
- src/data/list/List.ts
- src/data/onboarding/OnboardingHelper.ts
- src/data/onboarding/data.ts
- src/data/payments/PaymentHelper.ts
- src/data/profiles/ProfileHelper.ts
- src/data/profiles/data.ts
- src/data/refunds/RefundHelper.ts
- src/data/subscription/SubscriptionHelper.ts
- src/errors/ApiError.ts
Deprecated methods/properties such as:
* `payment.isOpen()` (synonymous with `payment.status == PaymentStatus.open`)
* `list.count` (synonymous with `list.length`)
* `error.getMessage()` (synonymous with `error.message`)
1. Removing these methods/properties will be a breaking change.
2. Some of these methods/properties also exist in the PHP client, therefore removing them will also widen the gap between the two clients.
1. Consumers of an API expect every part of it to be significant. When a consumer sees that a list has both a `length` and a `count`, they might wonder "What is the difference between these two? Perhaps `length` is the number of elements in this array, where `count` is the total number of elements available?" Methods/properties with such simple synonyms can cause …
> Deprecate predictable helper methods

- src/binders/chargebacks/ChargebacksBinder.ts
- src/binders/customers/CustomersBinder.ts
- src/binders/customers/mandates/CustomerMandatesBinder.ts
- src/binders/customers/payments/CustomerPaymentsBinder.ts
- src/binders/customers/subscriptions/CustomerSubscriptionsBinder.ts
- src/binders/methods/MethodsBinder.ts
- src/binders/orders/OrdersBinder.ts
- src/binders/orders/orderlines/OrderLinesBinder.ts
- src/binders/orders/shipments/OrderShipmentsBinder.ts
- src/binders/payments/PaymentsBinder.ts
- src/binders/payments/captures/PaymentCapturesBinder.ts
- src/binders/payments/chargebacks/PaymentChargebacksBinder.ts
- src/binders/payments/refunds/PaymentRefundsBinder.ts
- src/binders/permissions/PermissionBinder.ts
- src/binders/profiles/ProfilesBinder.ts
- src/binders/refunds/RefundsBinder.ts
- src/binders/refunds/orders/OrderRefundsBinder.ts
- src/binders/subscriptions/SubscriptionsBinder.ts
- src/binders/subscriptions/payments/SubscriptionPaymentsBinder.ts
Deprecated endpoint aliases such as:
* `client.payments.all` (which is synonymous with `client.payments.page`)
* `client.payments.delete` (which is synonymous with `client.payments.cancel`)
This is another breaking change.
The pros of #233 apply here as well:
1. Aliases are a potential cause for confusion.
2. A narrower API promotes discoverability.
3. This removal promotes consistency in code which uses this library.
I've chosen `page` over `all` or `list`. I don't like `all`, because the name is misleading: endpoints apply pagination, therefore `all` sometimes returns "some" instead of "all". `list` is a decent name; but `page` has the advantages of being consistent with the PHP client, and making it even more obvious that there is pagination in effect.
> Deprecate endpoint aliases

- src/NetworkClient.ts
- src/errors/ApiError.ts
1. If an error is thrown where the cause has a `response` property ‒ probably because it's an `AxiosError` ‒ the thrown error only uses that `response` property _if it is not `undefined`_. This should reduce the unhelpful `'error without a message'` errors by using the `message` property instead.
2. Fixed a refactoring mistake I made in #233. (Luckily, I can put some of the blame on my IDE.)
> ApiError improvement + fix

- package.json
- src/data/payments/PaymentHelper.ts
- src/errors/ApiError.ts
- yarn.lock
Removed Lodash as a dependency. While depending on Lodash is not at all problematic, our usage did not warrant the extra dependency.
> Lodash removal

- package.json
- src/binders/Binder.ts
Fixes a bug I introduced in #196.
That PR started using [the WHATWG `URL`](https://nodejs.org/api/url.html#the-whatwg-url-api). That API has been available since Node.js 7 and 6.13. However, it has only been available _on the global object_ (in other words: without importing it explicitly) since Node.js 10.
Well, it looks like Jest "fixed" this for us. Jest polyfilled `URL`, which meant the test passed on Node 6 even though the actual library did not work.
> Fix URL import for Node.js < 10

- src/data/payments/PaymentHelper.ts
Deprecated `payment.getPaymentUrl()`.
A breaking change, but:
* As this is synonymous with `payment.getCheckoutUrl()`, it is a potential cause for confusion.
* Since the  PHP client only has `getCheckoutUrl`, this removal make this library more consistent with the PHP client.
> Deprecate payment.getPaymentUrl

- src/data/payments/PaymentHelper.ts
`payment.isPaid()` is a predictable helper method I missed in #233.
> Deprecated payment.isPaid

- src/binders/customers/payments/parameters.ts
- src/binders/methods/MethodsBinder.ts
- src/binders/orders/shipments/OrderShipmentsBinder.ts
- src/binders/paymentLinks/PaymentLinksBinder.ts
- src/binders/payments/captures/parameters.ts
- src/binders/permissions/PermissionBinder.ts
`page` was selected as the preferred method name over `list` and `all` in #234. This PR re-introduces `list` as the preferred method name _for endpoints which don't paginate_.
Those endpoints are:
* [List methods](https://docs.mollie.com/reference/v2/methods-api/list-methods)
* [List shipments](https://docs.mollie.com/reference/v2/shipments-api/list-shipments) (for which the documentation does not explicitly mention that it does not paginate, but according to my tests it doesn't)
* [List permissions](https://docs.mollie.com/reference/v2/permissions-api/list-permissions)
The `iterate` method does not exist for these endpoints, either.
> Made list the preferred method for endpoints which don't paginate

- package.json
- src/binders/orders/OrdersBinder.ts
- src/binders/orders/parameters.ts
- src/binders/orders/shipments/OrderShipmentsBinder.ts
- src/binders/payments/captures/PaymentCapturesBinder.ts
- src/binders/payments/captures/parameters.ts
- src/binders/payments/parameters.ts
- src/binders/refunds/orders/OrderRefundsBinder.ts
- src/data/Issuer.ts
- src/data/global.ts
- src/data/payments/data.ts
This PR includes a few updates to the types for orders and payments. Most notably, the `payment` field for the order creation parameters is more accurate[[doc]](https://docs.mollie.com/reference/v2/orders-api/create-order#payment-parameters).
Additionally, this PR bumps the version to 3.6.0-beta.2, as I intend to publish immediately (on the _beta_ tag).
> Update order and payment types

- src/binders/methods/parameters.ts
This adds the missing `includeWallets` property to the `ListParameters` interface used by `mollie.methods.list`.
> Add `includeWallets` to ListParameters interface

- .eslintrc
- package.json
- src/communication/NetworkClient.ts
- src/plumbing/iteration/DemandingIterator.ts
- yarn.lock
* Makes Mollie ESLint configuration (`@mollie/eslint-config-typescript`) work with ESLint 8 by enforcing a later version of `eslint-plugin-import`.
* Reduces the length of `.eslintrc`.
> Cleanup ESLint setup

- src/binders/methods/parameters.ts
The Mollie API expects `orderLineCategories` in the list methods endpoint to be [a comma-separated list](https://docs.mollie.com/reference/v2/methods-api/list-methods#parameters). However, an array of strings is the more JavaScript-native type here, and the `NetworkClient` will join it anyway.
This is not a breaking change, as `orderLineCategories` was introduced in #279, which has not yet been released.
> Change orderLineCategories in the methods binder to an array

- src/data/Helper.ts
- tests/unit/inspect.test.ts
Inspecting objects (payments, customers, subscriptions, etc.) would throw an error on Node.js < 12, because the `inspect.custom` implementation relied on both `Object.entries` and `Object.fromEntries`.
> Fix bug on Node.js < 12

- CHANGELOG.md
- package.json
Bump version to 3.7.0.
Most notably, this version includes [retrying functionality](https://github.com/mollie/mollie-api-node/pull/294) and [an optimised iteration API](https://github.com/mollie/mollie-api-node/pull/280).
[A beta version](https://www.npmjs.com/package/@mollie/api-client/v/3.7.0-beta.2) was released on 13 December 2022, and we haven't received any complaints about it. This version only differs from that one in its documentation and dependencies.
> Bump version to 3.7.0

- src/binders/orders/parameters.ts
- src/binders/payments/parameters.ts
- src/data/orders/data.ts
- src/data/payments/data.ts
- tests/unit/models/order.test.ts
- tests/unit/models/payment.test.ts
- tests/unit/resources/customers/payments.test.ts
- tests/unit/resources/orders.test.ts
- tests/unit/resources/payments.test.ts
- tests/unit/resources/subscriptions/payments.test.ts
fixes #326 
Adds `cancelUrl` to order and payment. Field was added in [December 2022](https://docs.mollie.com/changelog/v2/changelog#december-2022)
> add cancelUrl to order and payment

- .github/workflows/codeql.yml
- .github/workflows/test.yml
- README.md
- package.json
In accordance with the discussion [here](https://github.com/mollie/mollie-api-node/pull/338), this raises the minimum node version for the package to node 14.
It also updates some github actions versions (which should have no effect).
The CI is now also configured to run on node 20.
This update will require the repo settings to be updated to expect the correct checks.
> update required node version [breaking]

- src/Options.ts
- src/createMollieClient.ts
- tests/unit/createMollieClient.test.ts
Previously, not setting `apiKey` or `accessToken` to an appropriate value would result in a generic error. After this PR, an accidental empty string (`createMollieClient({ apiKey: '' })`) gives a distinct error from no value at all (`createmollieClient({})`).
I suspect this is what happened in #349, and I hope this will prevent some headaches in the future.
> More helpful error in createMollieClient for missing credentials

- jest.config.js
Previously, some tests were skipped on older Node.js versions because they rely on Nock, which is unsupported by Node.js < 8.0.0.
We are currently figuring out which Node.js versions 4.0.0 of the client will support, but we plan on raising it to at least 8.0.0. We can thus safely run all tests unconditionally.
> Unconditionally run all tests

- src/binders/chargebacks/ChargebacksBinder.ts
- src/binders/customers/CustomersBinder.ts
- src/binders/customers/mandates/CustomerMandatesBinder.ts
- src/binders/customers/payments/CustomerPaymentsBinder.ts
- src/binders/customers/subscriptions/CustomerSubscriptionsBinder.ts
- src/binders/methods/MethodsBinder.ts
- src/binders/orders/OrdersBinder.ts
- src/binders/orders/orderlines/OrderLinesBinder.ts
- src/binders/orders/shipments/OrderShipmentsBinder.ts
- src/binders/payments/PaymentsBinder.ts
- src/binders/payments/captures/PaymentCapturesBinder.ts
- src/binders/payments/chargebacks/PaymentChargebacksBinder.ts
- src/binders/payments/refunds/PaymentRefundsBinder.ts
- src/binders/permissions/PermissionsBinder.ts
- src/binders/profiles/ProfilesBinder.ts
- src/binders/refunds/RefundsBinder.ts
- src/binders/refunds/orders/OrderRefundsBinder.ts
- src/binders/subscriptions/SubscriptionsBinder.ts
- src/binders/subscriptions/payments/SubscriptionPaymentsBinder.ts
- src/createMollieClient.ts
- src/plumbing/alias.ts
- tests/unit/backwards-compatibitily.test.ts
We [removed snake_case aliases for client properties](//github.com/mollie/mollie-api-node/pull/314) and [aliases for endpoints](//github.com/mollie/mollie-api-node/pull/315). This PR re-introduces them, this time unenumerable and non-existent in the TypeScript types.
This will not do much for TypeScript users, they will still get a compile-time error. This merely affects JavaScript users who are still using deprecated aliases. See #319 for more discussion on this.
> Re-introduce runtime aliases

- src/errors/ApiError.ts
- tests/unit/resources/methods.test.ts
This PR removes `ApiError::getMessage`, `ApiError::getField`, and `ApiError::getStatusCode`:
```diff
try {
const payment = await mollieClient.payments.get(…);
} catch (error) {
-    console.warn(error.getMessage())
+    console.warn(error.message)
}
```
The functions were deprecated in eb0abd2c1e7c230e8f6e6634ce68a134e7bce6c5. The values returned by these functions are available as (public) properties.
> Cleanup ApiError

- src/data/customers/mandates/MandateHelper.ts
- src/data/onboarding/OnboardingHelper.ts
- src/data/payments/PaymentHelper.ts
- src/data/profiles/ProfileHelper.ts
- src/data/refunds/RefundHelper.ts
- src/data/subscriptions/SubscriptionHelper.ts
- tests/integration/orders.test.ts
- tests/integration/payments.test.ts
- tests/unit/models/onboarding.test.ts
- tests/unit/models/payment.test.ts
- tests/unit/models/profile.test.ts
- tests/unit/models/refund.test.ts
- tests/unit/models/subscription.test.ts
This PR removes deprecated helpers from `MandateHelper`, `OnboardingHelper`, `PaymentHelper`, `ProfileHelper`, `RefundHelper`, and `SubscriptionHelper`. These are functions with no or very little logic in them and can be easily avoided:
```diff
-if (payment.isOpen()) {
+if (payment.status == PaymentStatus.open) {
```
The functions were deprecated in eb0abd2c1e7c230e8f6e6634ce68a134e7bce6c5. I believe including them in the API produces more noise than convenience.
> Cleanup helpers

- src/binders/Binder.ts
- src/communication/NetworkClient.ts
- src/communication/TransformingNetworkClient.ts
- src/data/page/Page.ts
ECMAScript has [a length property](https://tc39.es/ecma262/#sec-properties-of-array-instances-length) which makes `count` unnecessary. `count` was deprecated in eb0abd2c1e7c230e8f6e6634ce68a134e7bce6c5.
```diff
-payments.page({ limit: 10 }).count
+payments.page({ limit: 10 }).length
```
> Remove Page::count

- src/communication/NetworkClient.ts
if you provided a path, you probably meant to include it in the full URL. Without a trailing slash it would be ignored.
> add endpoint normalization

- src/data/methods/data.ts
When using the method's `include` option, we expect the result to include a `pricing` or `issuers` property, which is an array of objects.
see https://docs.mollie.com/reference/get-method
This replaces https://github.com/mollie/mollie-api-node/pull/355 and resolves https://github.com/mollie/mollie-api-node/issues/316
> Methods: fix types for pricing and issuer

- CHANGELOG.md
- MIGRATION.md
- README.md
This PR adds a changelog for v4.0.0, assuming https://github.com/mollie/mollie-api-node/pull/358 will be included in it.
> Update changelog for v4.0.0

- CHANGELOG.md
- MIGRATION.md
- README.md
- src/data/global.ts
Fixes #357 
The reference list is taken from the [API docs for the get method](https://docs.mollie.com/reference/get-method).
1. **Added the following new payment methods to `PaymentMethod`**:
- alma
- bacs
- bancomatpay
- billie
- blik
- riverty
- satispay
- trustly
- twint
2. **Moved outdated payment methods to `HistoricPaymentMethod`**:
- giropay
- sofort
> Update payment methods

- package.json
It seems that the TypeScript compiler previously put the type definitions into `dist/types/src`, but now puts them in `dist/types`. This may have happened [during our recent upgrade of TypeScript](https://github.com/mollie/mollie-api-node/pull/360).
This PR updates package.json to use the new path.
Please do check my work!
> Change path of the types in package.json

- package.json
This PR makes `@types/node-fetch` a regular dependency instead of a dev one
As we are using and re-exporting types from this package, users of this client should install them as well. This dependency is not required for users who don't use TypeScript and thus don't rely on the types, but I don't think anyone would mind the overhead.
> @types/node-fetch dependency

- README.md
This is the current example for async iterators:
```ts
// Iterate over all payments.
for await (let payment in mollieClient.payments.iterate()) {
// (Use break to end the loop prematurely.)
}
```
This has two issues, one being a mistake and one being a style issue.
1. Mistake: It should be `of` rather than `in`.
2. Style: The example should recommend using `const` rather than `let`.
Usually when iterating over payments we do not expect them to be reassigned within the for block.
If anyone would for some reason, it would be specific to their implementation and they would know to change it to 'let'.
Preferring const here is in line with the `prefer-const` [rule from eslint](https://archive.eslint.org/docs/4.0.0/rules/prefer-const).
> Fix Documentation for async iterators in README

- src/data/orders/OrderHelper.ts
- src/plumbing/resolveIf.ts
This resolves https://github.com/mollie/mollie-api-node/issues/391
This implements the proposed solution of properly`Promise.resolve` and consistent use of `resolveIf`, as discussed in the issue.
Supersedes #398
> Fix: order.getPayments() does not work

- src/binders/payments/chargebacks/PaymentChargebacksBinder.ts
This resolves https://github.com/mollie/mollie-api-node/issues/395.
The incorrect assertion was used for chargebacks.
supersedes #399
> Fix: faulty id assertion

- src/data/payments/PaymentHelper.ts
The `isRefundable` helper on a payment actually never returned `false`, because the strict `null` comparison is incorrect.
If `amountRemaining` is not provided (as it is for non-refundable payments), it is `undefined` rather than `null`.
This is also reflected in `canBeRefunded`, which is correct and should be used instead.
To not make this a breaking change, I fixed the behaviour and deprecated the method.
supersedes #385
> Fixed and deprecated payment.isRefundable

- .github/workflows/test.yml
Github Actions will deprecate the ubuntu-20.04 image, we should always run on ubuntu-latest.
> NTR: Update github actions image to ubuntu-latest

- src/data/global.ts
Field can be found in details for get payment: https://docs.mollie.com/reference/get-payment
The docs are still not consistent on which fields are `required` and `optional`, but here it's pretty clear: The docs say it is only included 'if the adressee is an organization'.
fixes #410
> add `organizationName` to Address Object

- src/binders/paymentLinks/PaymentLinksBinder.ts
- src/binders/paymentLinks/parameters.ts
- src/data/paymentLinks/data.ts
There were several missing types in payment links api.
This fixes #415
> Added missing payment link params

- src/data/paymentLinks/data.ts
- tests/__nock-fixtures__/paymentLinks.json
As discussed [here](https://github.com/mollie/mollie-api-node/issues/415#issuecomment-2747217823), the `updatedAt`  field in payment links always returns null should not exist.
Since it has been in the package for more than 3 years I decided on deprecating it, rather than removing it straight away.
> Remove `updatedAt` field from payment links

- src/binders/payments/parameters.ts
This adds several [method specifc params](https://docs.mollie.com/reference/extra-payment-parameters#paypal), which are currently missing.
It also updates the reference links and doc texts to the current version(s).
In the long run we might want to improve this using discriminated unions, but for now this consistent with past implementations.
> Add missing method specific parameters

- src/binders/customers/payments/parameters.ts
The types of `payment.create` have been extensively updated recently.
Unfortunately `customerPayments.create` was neglected, even though it supports the same parameters (with the exception of `customerId`, as it's part of the request URL.
This PR fixes this mismatch and ensures long-term compatibility by importing and using the same types.
This fixes #441
> sync Params of payments.create to customersPayments.create
